### PR TITLE
[DX] - Added new UI

### PR DESCRIPTION
**Pull request by mickaelandrieu**
I think elcodi docs deserve better than a common theme for website.

So this is my proposal for docs.elcodi.io:

home
search
submenus

The base of the them is bootstrap 3, I just override some css classes.

Also, I have added a footer and some meta (see mkdocs.yml and mkdocs configuration).

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @mmoreram, tell me if this need more work :)

**Comment by mmoreram** [comment]
@mickaelandrieu I'm having problems with extensions...

```
Building documentation to directory: site
Directory site contains stale files. Use --clean to remove them.
ERROR - Error building page index.md
[E 150602 11:21:37 build:221] Error building page index.md
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 9, in <module>
    load_entry_point('mkdocs==0.12.1', 'console_scripts', 'mkdocs')()
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/main.py", line 77, in run_main
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/main.py", line 52, in main
    build(config, clean_site_dir=clean_site_dir)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 252, in build
    build_pages(config)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 219, in build_pages
    _build_page(page, config, site_navigation, env, dump_json)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 173, in _build_page
    extensions=config['markdown_extensions'], strict=config['strict']
  File "/usr/local/lib/python2.7/dist-packages/mkdocs/build.py", line 36, in convert_markdown
    extensions=extensions
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 195, in registerExtensions
    % (ext.__class__.__module__, ext.__class__.__name__))
TypeError: Extension "__builtin__.dict" must be of type: "markdown.Extension"
```

**Comment by mickaelandrieu** [comment]
@mmoreram maybe do you need to update your version of mkdocs ?

``` bash
docs git:(new-ui) mkdocs --version
mkdocs, version 0.13.2
```

Try this:

``` bash
mkdocs build --clean
mkdocs serve # should be ok now
mkdocs gh-deploy --clean # if pull request is ok
```

**Comment by mmoreram** [comment]
Updated, thanks.

Menus are not being built properly... What is this extension called `admonition` ?

**Comment by mickaelandrieu** [comment]
admonition extension is not required (allow some specific markdown), let me update my pull request :)

For the menus, I don't know (works from my side, and on a friend computer): maybe this is a css cache issue ? did you have any javascript or http fail ?

**Comment by mickaelandrieu** [comment]
@mmoreram any news about this pull request ? What do I need to do to help you merge this one ?

**Comment by mmoreram** [comment]
@mickaelandrieu I need some time. ASAP I will revise and merge. Thanks.

**Comment by mmoreram** [comment]
Pending! :) I did not forget this one! :)

**Comment by mmoreram** [comment]
@mickaelandrieu This PR breaks some parts of the documentation.
- If you check the original top bar from the documentation, inside `Book` tab, you can see that all entries have another level of menu. This feature has been removed.
- The search box has been removed. Why?

**Comment by mickaelandrieu** [comment]
@mmoreram I will take a look on it this week end, but imo the "bootstrap 3" theme dont embed search feature by default.

For Book tab, I think again that bootstrap is unable to manage 3 levels of page.. this need more (integration) work from my part :)

**Comment by mmoreram** [comment]
This feature is already on master.

Thanks @mickaelandrieu for that great effort!

**Pull request closed without merging**
