### PR TITLE
introduce corrections to sitemap.md

### PR DESCRIPTION
**Pull request by cordoval**
| Q | A |
| --- | --- |
| Notes | :+1: :older_man: |

corrections

### CODE REVIEW

**Comment by mmoreram** [comment]
@cordoval Can you rebase, please? :D

**Comment by cordoval** [comment]
cc @sstok it is true https://github.com/gushphp/gush/issues/410

**Comment by cordoval** [comment]
ok on it cc @mmoreram

**Comment by cordoval** [comment]
bump @mmoreram

**Pull request merged**
