### PR TITLE
updated quickstart

### PR DESCRIPTION
**Pull request by mickaelandrieu**
To be merged as soon as possible ;)

### CODE REVIEW

**Comment by xphere** [comment]
Celebrate! :dancer:

**Comment by mickaelandrieu** [comment]
I can't merge, @mmoreram don't let me touch his "baby" :'(

**Comment by mickaelandrieu** [comment]
ping @mmoreram this pull request is very easy to review ;)

**Comment by mmoreram** [comment]
right :D Thanks man!

**Pull request merged**
